---
title: "cross-correlation"
author: "Wolfgang Giese"
date: "7/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(tidyverse)
library(ggplot2)
```

## Read data

```{r read_data}
#filepath <- "/home/wgiese/image-data-workflows/vascu-ec-app/merged.csv"
#filepath <- "/home/wgiese/Data/Olya/pSMAD158_intensity_analysis/siRNA/siCTRL/4h/6dyn/BSA 0.1%/analysis_output/merged.csv"
filepath <- "/home/wgiese/Data/Olya/pSMAD158_intensity_analysis/no transfection/16h flow/6dyn/BSA 0.1%/analysis_output/merged.csv"

ec_features <- read.csv(file = filepath)
#summary(ec_features)
```

## Select features

You can also embed plots, for example:

```{r select_features, echo=TRUE}
print(head(ec_features))
#ec_features_select <- ec_features[,c("area", "perimeter", "mean_expression", "major_axis_length", "minor_axis_length", "shape_orientation", "angle_rad")]
ec_features_select <- ec_features[,c("area", "perimeter",  "major_axis_length", "minor_axis_length", "shape_orientation", "angle_rad", "shape_orientation_nuc")]
for(i in 1:nrow(ec_features_select)) {
    row <- ec_features_select[i,]
    shape_orientation_adj = row$shape_orientation
    shape_orientation_nuc_adj = row$shape_orientation_nuc
    if( row$shape_orientation < 3.1415926/2.0) {
      shape_orientation_adj = row$shape_orientation + 3.1415926
    }
    if( row$shape_orientation_nuc< 3.1415926/2.0) {
      shape_orientation_nuc_adj = row$shape_orientation_nuc + 3.1415926
    }
    ec_features_select[i,"shape_orientation_adj"] = shape_orientation_adj 
    ec_features_select[i,"shape_orientation_nuc_adj"] = shape_orientation_nuc_adj 
    # do stuff with row
}
print(ec_features_select[3,])


print(head(ec_features_select))
#plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.


```{r feature_pair_plot, echo=TRUE}
pairs(ec_features_select)
#plot(pressure)ec_features_select <- ec_features[,c("area", "perimeter", "mean_expression", "major_axis_length", "minor_axis_length", "shape_orientation", "flow_alignment")]
#plot(pressure)


```


```{r feature_pair_plot2, echo=TRUE}
#ec_features_select2 <- ec_features[,c("area", "perimeter", "mean_expression", "shape_orientation", "angle_rad")]
ec_features_select2 <- ec_features[,c("area", "perimeter", "shape_orientation", "angle_rad")]
pairs(ec_features_select2)
#plot(pressure)
#plot(pressure)
```


```{r feature_polarity_plot, echo=TRUE}
bin_size <- 10
    ggplot() +
      geom_histogram(aes(ec_features_select$angle_rad*180.0/3.1415926),
                     breaks = seq(0, 360, bin_size),
                     colour = "black",
                     fill = "grey80") +
      ggtitle("cell nuclei-golgi polarity") +
      theme(axis.text.x = element_text(size = 18)) +
      coord_polar(start = -pi/2.0, direction = -1) +
      scale_x_continuous(limits = c(0, 360),
                         breaks = (c(0, 90, 180, 270))) +
      theme_minimal(base_size = 14) +
      xlab(paste0("n = ", length(ec_features_select$angle_rad))) +
      ylab("") +
      theme(axis.text.y=element_blank()) +
      scale_y_sqrt()
```


```{r feature_alignment_plot, echo=TRUE}
bin_size <- 10
    ggplot() +
      geom_histogram(aes(ec_features_select$shape_orientation_adj*180.0/3.1415926),
                     breaks = seq(0, 360, bin_size),
                     colour = "black",
                     fill = "grey80") +
      ggtitle("cell shape orientation") +
      theme(axis.text.x = element_text(size = 18)) +
      coord_polar(start = -pi/2.0, direction = -1) +
      scale_x_continuous(limits = c(0, 360),
                         breaks = (c(0, 90, 180, 270))) +
      theme_minimal(base_size = 14) +
      xlab(paste0("n = ", length(ec_features_select$shape_orientation))) +
      ylab("") +
      theme(axis.text.y=element_blank()) +
      scale_y_sqrt()
```

```{r feature_nuclei_alignment_plot, echo=TRUE}
bin_size <- 10
    ggplot() +
      geom_histogram(aes(ec_features_select$shape_orientation_nuc_adj*180.0/3.1415926),
                     breaks = seq(0, 360, bin_size),
                     colour = "black",
                     fill = "grey80") +
      ggtitle("nuclei shape orientation") +
      theme(axis.text.x = element_text(size = 18)) +
      coord_polar(start = -pi/2.0, direction = -1) +
      scale_x_continuous(limits = c(0, 360),
                         breaks = (c(0, 90, 180, 270))) +
      theme_minimal(base_size = 14) +
      xlab(paste0("n = ", length(ec_features_select$shape_orientation_nuc))) +
      ylab("") +
      theme(axis.text.y=element_blank()) +
      scale_y_sqrt()
```

