---
title: "stats teststion"
author: "Wolfgang Giese"
date: "7/26/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#library(tidyverse)
library(circular)
#library(NPCirc)
library(CircStats)
library(ggplot2)
```

## R Markdown

```{r read_data}
#filepath <- "/home/wgiese/image-data-workflows/vascu-ec-app/merged.csv"
filepath <- "../test_data/stack_EC_microscopy/120821 BSA #01.csv"
ec_features <- read.csv(file = filepath)
#summary(ec_features)
```

```{r rayleigh_test}
res <- r.test(ec_features$angle_deg, degree=TRUE) 
print(res)
print(res$p.value)

```

```{r rayleigh_test_mu}
res <- v0.test(ec_features$angle_deg, mu0=180, degree=TRUE) 
print(res)
print(res$p.value)
```

```{r plot_circular}
#t <-circular(seq(0, 2 * pi, length = 500))
#plot(t, shrink = 1.5,pch = NA,axes=FALSE,)
#axis.circularLL(at=circular(rad(c(90))), labels="0",tcl.text=0.2,
#                tick=TRUE,
#                tcl=0.1,
#                cex = 0.9)
#lines(t+pi/2, fmix, shrink = 1, lwd = 1,lty=2)
#data.vm <- rvonmises(n=100, mu=circular(0), kappa=3) 

data.vm <- circular(ec_features$angle_rad) 

plot(data.vm, axes=FALSE, ticks=FALSE)
print(data.vm)

```

```{r plot_arrows}

filepath <- "../test_data/stack_EC_microscopy/120821 BSA #01.csv"

ec_features <- read.csv(file = filepath)
feature_circular <- unlist(ec_features["angle_rad"])*180.0/pi
bins = 10
bin_size = 360/bins
plot_title <- "test"
test_size <- 14

p <- ggplot()

p <- p + ggtitle(plot_title) +
        theme(plot.title = element_text(size = 18, face = "bold")) +
        theme(axis.text.x = element_text(size = 18)) +
        coord_polar(start = -pi/2.0, direction = -1) +
        scale_x_continuous(limits = c(0, 360),
                       breaks = (c(0, 90, 180, 270))) +
        scale_y_continuous(limits = c(0, 1.1))
#        theme_minimal(base_size = text_size)
        #xlab(sprintf("number of cells = : %s \n polarity index: %s, %s, \n condition: %s", length(feature_circular), polarity_index, p_value, input$exp_condition)) +
#        ylab("polarity index")

      p <- p +
          geom_histogram(aes(x = feature_circular, y = ..ncount..),
                        breaks = seq(0, 360, bin_size),
                        colour = "black",
                        fill = "black",
                        alpha = 0.5)
      
      p + geom_point(aes(x = feature_circular, y = 1))
                #geom_histogram(aes(x = feature_circular, y = ..ncount..),
                #        colour = "black",
                #        fill = "black",
                #        alpha = 0.5)
                 

p

```






